version: '3.7'

services:
  dev:
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
      - ./dist:/usr/src/app/dist
    environment:
      NODE_ENV: development

  ci:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
      - /usr/src/app/dist
    environment:
      NODE_ENV: production

networks:
  service_net:
